import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../../components/Sidebar/Sidebar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main-body">
        {children}</body>
    </html>
  );
}
